#ifndef AUGMENTATION_H
#define AUGMENTATION_H

#include "../inc/common.h"

enum BODY_PART
{
    BODY_PART__NONE,

    BODY_PART__LEFT_HAND,
    BODY_PART__RIGHT_HAND,
    BODY_PART__LEFT_LEG,
    BODY_PART__RIGHT_LEG,
    BODY_PART__TAIL,
    BODY_PART__TORSO,

    BODY_PART__COUNT
};

enum AUGMENTATION
{
    AUGMENTATION__NONE,

    AUGMENTATION__SPRING,
    AUGMENTATION__TRACK,
    AUGMENTATION__TAIL,
    AUGMENTATION__MINIBOT,
    AUGMENTATION__WINGS,
    
    AUGMENTATION__ARM,
    AUGMENTATION__BLADE,
    AUGMENTATION__CANNON,
    AUGMENTATION__COIL,
    AUGMENTATION__DRILL,
    AUGMENTATION__FLAME,
    AUGMENTATION__FREEZE,
    AUGMENTATION__GUN,
    AUGMENTATION__HAMMER,
    AUGMENTATION__LASER,
    AUGMENTATION__WHIP,

    AUGMENTATION__COUNT,
};

int get_augmentation_body_part(int augmentation);
char* get_body_part_name(int body_part);
char* get_augmentation_name(int augmentation);

#endif
