#ifndef SKILL_H
#define SKILL_H

#include "../inc/common.h"
#include "../inc/vec.h"
#include "../inc/textures.h"

enum SKILL
{
    SKILL__NONE,

    SKILL__ATTACK_DIR,
    SKILL__NO_ATTACK,

    SKILL__USE,
    SKILL__MOVE,
    SKILL__PICK_ITEM_CLOSE,

    SKILL__SHOOT_PROJECTILE_FLY,
    SKILL__SHOOT_PROJECTILE_SQUIRREL,

    SKILL__CHARGE,
    SKILL__JUMP,
    SKILL__BURROW,

    SKILL__CHARGE_AND_JUMP,

    SKILL__PUSH,
    SKILL__PUNCH,
    SKILL__CHARGE_AND_PUNCH,
    SKILL__DRILL,
    SKILL__DRILL_FLOOR,

    SKILL__BRANCHING_BOLT,
    SKILL__STUNNING_BOLT,
    SKILL__COOKING_BOLT,
    SKILL__ELECTRIFY_FLOOR,

    SKILL__SCORCH_WITH_FIRE,
    SKILL__SPEW_TAR_BALL,
    SKILL__FIRE_WELD_FLOOR,
    SKILL__ROCKET_JUMP,
    SKILL__ROCKET_DASH,

    SKILL__PENETRATING_BEAM,
    SKILL__BOUNCING_BEAM,
    SKILL__FOCUSED_BEAM,
    SKILL__LASER_WELD_FLOOR,

    SKILL__ICE_BLOCK,
    SKILL__ICE_WALL,
    SKILL__ICE_PROJECTILE,
    SKILL__FREEZE_FLOOR,
    SKILL__ICE_BUNKER,

    SKILL__SIMPLE_SHOT,
    SKILL__SNIPER_SHOT,
    SKILL__POINT_BLANK_SHOT,
    SKILL__HEAD_SHOT,
    SKILL__STUNNING_SHOT,
    SKILL__HARPOON_SHOT,

    SKILL__HIGH_PROJECTILE,
    SKILL__HIGH_EXPLOADING_PROJECTILE,
    SKILL__DOUBLE_JUMP,
    SKILL__RICOSHET,
    SKILL__NEST,

    SKILL__SWING,
    SKILL__NAIL,
    SKILL__JUMP_AND_NAIL,
    SKILL__NAIL_FLOOR,

    SKILL__THROW,
    SKILL__JUMP_AND_CARRY,
    SKILL__BURROW_AND_GTFO,

    SKILL__THRUST,
    SKILL__PENETRATING_THRUST,
    SKILL__HEAD_SLICE,
    SKILL__BURROW_AND_SLICE,
    SKILL__CHARGE_AND_SLICE,

    SKILL__WHIP_SMACK_WEIRD,
    SKILL__WHIP_PULL_WEIRD,
    SKILL__WHIP_SMACK,
    SKILL__WHIP_DRAG,
    SKILL__WHIP_PULL,
    SKILL__WHIP_TURN,
    SKILL__ARM_TURN,
    SKILL__WHIP_YEET,
    SKILL__ARM_YEET,
    SKILL__BURY,

    SKILL__LAUNCH_MINIBOT,
    SKILL__MINIBOT_MERGE,

    SKILL__CHARGE_AND_THROW,
    SKILL__DRAG,
    SKILL__PULL,
    SKILL__PUSH_DAMAGE,
    SKILL__THROW_DAMAGE,
    SKILL__DRAG_DAMAGE,
    SKILL__JUMP_DAMAGE_AROUND,
    SKILL__DAMAGE_1,
    SKILL__DAMAGE_3,
    SKILL__CHARGE_AND_DAMAGE_3,
    SKILL__PROJECTILE_LINE_1,
    SKILL__PROJECTILE_ARCH_1,
    SKILL__PROJECTILE_LINE_AROUND,
    SKILL__LAUNCH_MINIBOT_MEGASPIDER,

    // SKILL__TURRET_LASER,
    // SKILL__TURRET_BOMB,
    // SKILL__TURRET_PROJECTILE,

    // SKILL__KILL_AROUND,

    // SKILL__ENVIRONMENT_FALLING_STALACTITE,
    // SKILL__ENVIRONMENT_EMERGE_WATER,
    // SKILL__ENVIRONMENT_EMERGE_PIT,
    // SKILL__ENVIRONMENT_EMERGE_BURROW,
    // SKILL__ENVIRONMENT_EMERGE_PIPE,
    // SKILL__ENVIRONMENT_COLLAPSE_BURROW,
    // SKILL__ENVIRONMENT_CONV_BELT,

    SKILL__COUNT
};

int is_skill_two_target(int skill);
int get_skill_action_points(int skill);
char* get_in_game_skill_name(int skill);
char* get_debug_skill_name(int skill);
char* get_description_from_skill(int skill, int i);
Texture* get_skill_hud_texture(int skill, Textures* textures);

#endif
